[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0xf74894376ff6df0a71e016622e63e572ef3976f566afcc2c81bcec09394e664c'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]